### ISSUE TITLE
Reg: After stemcell installation not able to execute stemcell command.

### ISSUE THREAD

**Issue by harikrishna1210** [ankurcha/stemcell#6]
Hi,
    I want to create the own stemcell with centos.For that i saw this link in https://github.com/ankurcha/stemcell.And i followed for installation.
## Step1:

 gem install stemcell
Successfully installed stemcell-0.0.1
1 gem installed
Installing ri documentation for stemcell-0.0.1...
Installing RDoc documentation for stemcell-0.0.1...
## Step2

I installed ruby through the rbenv.Then executed this command in terminal.
rbenv rehash
## Step3:

stemcell build
stemcell: command not found

Here is the problem why it's saying "stemcell: command not found".Incase i installed any other packages like bosh-gen/bosh,After i executed "rbenv rehash" it's working fine.I able to use that commands.Except stemcell,Pls tell me if any thing i did wrong in stemcell usage.

Thanks,
Hari.

**Comment by ankurcha** [comment]
I don't really know what rbenv expects but as far as i can see. This is how i have been installing stemcell on a bare ruby environment.
`cd stemcell && gem build *.gemspec && gem install *.gem`

Is there some special magic that rbenv expects of the gems?

**Comment by ankurcha** [comment]
I tried replicating this on a fresh vm but it ran just fine. Could there be something else interacting? Also, try pulling the head of the repo and doing a install.
`bundle install` or `gem build *.gemspec && gem install *.gem`
